stages:
  - test
  - publish

test:
  stage: test
  image: mhart/alpine-node:8
  script:
    - echo 1
  tags:
    - sl-frontend

publish:
  stage: publish
  image: mhart/alpine-node:8
  variables:
    NPM_AUTH_KEY: $CI_JOB_TOKEN
  script:
    - env
    - npm version $CI_COMMIT_REF_NAME && npm publish
  only:
    refs:
      - tags
  tags:
    - sl-frontend